name: rampvis-ui
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.8.3
  - readline=8.0
  - setuptools=50.3.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.4.3
    - chardet==3.0.4
    - click==7.1.2
    - dnspython==2.0.0
    - email-validator==1.1.1
    - flask==1.1.2
    - flask-login==0.5.0
    - flask-migrate==2.5.3
    - flask-sqlalchemy==2.4.3
    - flask-wtf==0.14.3
    - gunicorn==20.0.4
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - mako==1.1.3
    - markupsafe==1.1.1
    - pillow==7.2.0
    - pyjwt==1.7.1
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - requests==2.24.0
    - selenium==3.141.0
    - six==1.15.0
    - sqlalchemy==1.3.20
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - wtforms==2.3.3