export const covidIndicators = [
  {
    label: "Daily Deaths",
    value: "new_deaths",
  },
  {
    label: "Daily Cases",
    value: "new_cases",
  },
  {
    label: "Daily Deaths per million",
    value: "new_deaths_per_million",
  },
  {
    label: "Daily Cases per million",
    value: "new_cases_per_million",
  },
  {
    label: "Biweekly Cases per million",
    value: "biweekly_cases_per_million",
  },
  {
    label: "Biweekly Deaths per million",
    value: "biweekly_deaths_per_million",
  },

  {
    label: "Biweekly Cases",
    value: "biweekly_cases",
  },
  {
    label: "Biweekly Deaths",
    value: "biweekly_deaths",
  },
  {
    label: "Weekly Cases per million",
    value: "weekly_cases_per_million",
  },
  {
    label: "Weekly Deaths per million",
    value: "weekly_deaths_per_million",
  },
  {
    label: "Weekly Cases",
    value: "weekly_cases",
  },
  {
    label: "Weekly Deaths",
    value: "weekly_deaths",
  },
];

export const similarityMeasures = [
  {
    label: "Euclidean Distance",
    value: "euclidean",
  },
  {
    label: "Manhattan Distance",
    value: "manhattan",
  },
  {
    label: "Chebyshev Distance",
    value: "chebyshev",
  },
  {
    label: "Dynamic Time Warping Distance",
    value: "dtw",
  },
  {
    label: "Longest Common Subsequence Distance",
    value: "lcs",
  },

  {
    label: "Pearson Correlation",
    value: "pearson",
  },
  /*
  {
    label: "Cosine Distance",
    value: "cosine"
  },
  {
    label: "Jensen Shannon",
    value: "jensenshannon"
  },
  */

  {
    label: "Bray-Curtis",
    value: "braycurtis",
  },
];

export const continents = [
  {
    value: "Africa",
  },
  {
    value: "Asia",
  },
  {
    value: "Oceania",
  },
  {
    value: "Europe",
  },
  {
    value: "North America",
  },
  {
    value: "South America",
  },
];

export const autoFillList = [
  { label: "Afghanistan", continent: "Asia" },
  { label: "Albania", continent: "Europe" },
  { label: "Algeria", continent: "Africa" },
  { label: "Andorra", continent: "Europe" },
  { label: "Angola", continent: "Africa" },
  { label: "Anguilla", continent: "North America" },
  { label: "Antigua and Barbuda", continent: "North America" },
  { label: "Argentina", continent: "South America" },
  { label: "Armenia", continent: "Asia" },
  { label: "Aruba", continent: "North America" },
  { label: "Australia", continent: "Oceania" },
  { label: "Austria", continent: "Europe" },
  { label: "Azerbaijan", continent: "Asia" },
  { label: "Bahamas", continent: "North America" },
  { label: "Bahrain", continent: "Asia" },
  { label: "Bangladesh", continent: "Asia" },
  { label: "Barbados", continent: "North America" },
  { label: "Belarus", continent: "Europe" },
  { label: "Belgium", continent: "Europe" },
  { label: "Belize", continent: "North America" },
  { label: "Benin", continent: "Africa" },
  { label: "Bermuda", continent: "North America" },
  { label: "Bhutan", continent: "Asia" },
  { label: "Bolivia", continent: "South America" },
  { label: "Bonaire Sint Eustatius and Saba", continent: "North America" },
  { label: "Bosnia and Herzegovina", continent: "Europe" },
  { label: "Botswana", continent: "Africa" },
  { label: "Brazil", continent: "South America" },
  { label: "British Virgin Islands", continent: "North America" },
  { label: "Brunei", continent: "Asia" },
  { label: "Bulgaria", continent: "Europe" },
  { label: "Burkina Faso", continent: "Africa" },
  { label: "Burundi", continent: "Africa" },
  { label: "Cambodia", continent: "Asia" },
  { label: "Cameroon", continent: "Africa" },
  { label: "Canada", continent: "North America" },
  { label: "Cape Verde", continent: "Africa" },
  { label: "Cayman Islands", continent: "North America" },
  { label: "Central African Republic", continent: "Africa" },
  { label: "Chad", continent: "Africa" },
  { label: "Chile", continent: "South America" },
  { label: "China", continent: "Asia" },
  { label: "Colombia", continent: "South America" },
  { label: "Comoros", continent: "Africa" },
  { label: "Congo", continent: "Africa" },
  { label: "Cook Islands", continent: "Oceania" },
  { label: "Costa Rica", continent: "North America" },
  { label: "Cote d'Ivoire", continent: "Africa" },
  { label: "Croatia", continent: "Europe" },
  { label: "Cuba", continent: "North America" },
  { label: "Curacao", continent: "North America" },
  { label: "Cyprus", continent: "Europe" },
  { label: "Czechia", continent: "Europe" },
  { label: "Democratic Republic of Congo", continent: "Africa" },
  { label: "Denmark", continent: "Europe" },
  { label: "Djibouti", continent: "Africa" },
  { label: "Dominica", continent: "North America" },
  { label: "Dominican Republic", continent: "North America" },
  { label: "Ecuador", continent: "South America" },
  { label: "Egypt", continent: "Africa" },
  { label: "El Salvador", continent: "North America" },
  { label: "Equatorial Guinea", continent: "Africa" },
  { label: "Eritrea", continent: "Africa" },
  { label: "Estonia", continent: "Europe" },
  { label: "Eswatini", continent: "Africa" },
  { label: "Ethiopia", continent: "Africa" },
  { label: "Faeroe Islands", continent: "Europe" },
  { label: "Falkland Islands", continent: "South America" },
  { label: "Fiji", continent: "Oceania" },
  { label: "Finland", continent: "Europe" },
  { label: "France", continent: "Europe" },
  { label: "French Polynesia", continent: "Oceania" },
  { label: "Gabon", continent: "Africa" },
  { label: "Gambia", continent: "Africa" },
  { label: "Georgia", continent: "Asia" },
  { label: "Germany", continent: "Europe" },
  { label: "Ghana", continent: "Africa" },
  { label: "Gibraltar", continent: "Europe" },
  { label: "Greece", continent: "Europe" },
  { label: "Greenland", continent: "North America" },
  { label: "Grenada", continent: "North America" },
  { label: "Guatemala", continent: "North America" },
  { label: "Guernsey", continent: "Europe" },
  { label: "Guinea", continent: "Africa" },
  { label: "Guinea-Bissau", continent: "Africa" },
  { label: "Guyana", continent: "South America" },
  { label: "Haiti", continent: "North America" },
  { label: "Honduras", continent: "North America" },
  { label: "Hong Kong", continent: "Asia" },
  { label: "Hungary", continent: "Europe" },
  { label: "Iceland", continent: "Europe" },
  { label: "India", continent: "Asia" },
  { label: "Indonesia", continent: "Asia" },
  { label: "Iran", continent: "Asia" },
  { label: "Iraq", continent: "Asia" },
  { label: "Ireland", continent: "Europe" },
  { label: "Isle of Man", continent: "Europe" },
  { label: "Israel", continent: "Asia" },
  { label: "Italy", continent: "Europe" },
  { label: "Jamaica", continent: "North America" },
  { label: "Japan", continent: "Asia" },
  { label: "Jersey", continent: "Europe" },
  { label: "Jordan", continent: "Asia" },
  { label: "Kazakhstan", continent: "Asia" },
  { label: "Kenya", continent: "Africa" },
  { label: "Kiribati", continent: "Oceania" },
  { label: "Kosovo", continent: "Europe" },
  { label: "Kuwait", continent: "Asia" },
  { label: "Kyrgyzstan", continent: "Asia" },
  { label: "Laos", continent: "Asia" },
  { label: "Latvia", continent: "Europe" },
  { label: "Lebanon", continent: "Asia" },
  { label: "Lesotho", continent: "Africa" },
  { label: "Liberia", continent: "Africa" },
  { label: "Libya", continent: "Africa" },
  { label: "Liechtenstein", continent: "Europe" },
  { label: "Lithuania", continent: "Europe" },
  { label: "Luxembourg", continent: "Europe" },
  { label: "Macao", continent: "Asia" },
  { label: "Madagascar", continent: "Africa" },
  { label: "Malawi", continent: "Africa" },
  { label: "Malaysia", continent: "Asia" },
  { label: "Maldives", continent: "Asia" },
  { label: "Mali", continent: "Africa" },
  { label: "Malta", continent: "Europe" },
  { label: "Marshall Islands", continent: "Oceania" },
  { label: "Mauritania", continent: "Africa" },
  { label: "Mauritius", continent: "Africa" },
  { label: "Mexico", continent: "North America" },
  { label: "Micronesia (country)", continent: "Oceania" },
  { label: "Moldova", continent: "Europe" },
  { label: "Monaco", continent: "Europe" },
  { label: "Mongolia", continent: "Asia" },
  { label: "Montenegro", continent: "Europe" },
  { label: "Montserrat", continent: "North America" },
  { label: "Morocco", continent: "Africa" },
  { label: "Mozambique", continent: "Africa" },
  { label: "Myanmar", continent: "Asia" },
  { label: "Namibia", continent: "Africa" },
  { label: "Nauru", continent: "Oceania" },
  { label: "Nepal", continent: "Asia" },
  { label: "Netherlands", continent: "Europe" },
  { label: "New Caledonia", continent: "Oceania" },
  { label: "New Zealand", continent: "Oceania" },
  { label: "Nicaragua", continent: "North America" },
  { label: "Niger", continent: "Africa" },
  { label: "Nigeria", continent: "Africa" },
  { label: "Niue", continent: "Oceania" },
  { label: "North Macedonia", continent: "Europe" },
  { label: "Northern Cyprus", continent: "Asia" },
  { label: "Norway", continent: "Europe" },
  { label: "Oman", continent: "Asia" },
  { label: "Pakistan", continent: "Asia" },
  { label: "Palau", continent: "Oceania" },
  { label: "Palestine", continent: "Asia" },
  { label: "Panama", continent: "North America" },
  { label: "Papua New Guinea", continent: "Oceania" },
  { label: "Paraguay", continent: "South America" },
  { label: "Peru", continent: "South America" },
  { label: "Philippines", continent: "Asia" },
  { label: "Pitcairn", continent: "Oceania" },
  { label: "Poland", continent: "Europe" },
  { label: "Portugal", continent: "Europe" },
  { label: "Qatar", continent: "Asia" },
  { label: "Romania", continent: "Europe" },
  { label: "Russia", continent: "Europe" },
  { label: "Rwanda", continent: "Africa" },
  { label: "Saint Helena", continent: "Africa" },
  { label: "Saint Kitts and Nevis", continent: "North America" },
  { label: "Saint Lucia", continent: "North America" },
  { label: "Saint Pierre and Miquelon", continent: "North America" },
  { label: "Saint Vincent and the Grenadines", continent: "North America" },
  { label: "Samoa", continent: "Oceania" },
  { label: "San Marino", continent: "Europe" },
  { label: "Sao Tome and Principe", continent: "Africa" },
  { label: "Saudi Arabia", continent: "Asia" },
  { label: "Senegal", continent: "Africa" },
  { label: "Serbia", continent: "Europe" },
  { label: "Seychelles", continent: "Africa" },
  { label: "Sierra Leone", continent: "Africa" },
  { label: "Singapore", continent: "Asia" },
  { label: "Sint Maarten (Dutch part)", continent: "North America" },
  { label: "Slovakia", continent: "Europe" },
  { label: "Slovenia", continent: "Europe" },
  { label: "Solomon Islands", continent: "Oceania" },
  { label: "Somalia", continent: "Africa" },
  { label: "South Africa", continent: "Africa" },
  { label: "South Korea", continent: "Asia" },
  { label: "South Sudan", continent: "Africa" },
  { label: "Spain", continent: "Europe" },
  { label: "Sri Lanka", continent: "Asia" },
  { label: "Sudan", continent: "Africa" },
  { label: "Suriname", continent: "South America" },
  { label: "Sweden", continent: "Europe" },
  { label: "Switzerland", continent: "Europe" },
  { label: "Syria", continent: "Asia" },
  { label: "Taiwan", continent: "Asia" },
  { label: "Tajikistan", continent: "Asia" },
  { label: "Tanzania", continent: "Africa" },
  { label: "Thailand", continent: "Asia" },
  { label: "Timor", continent: "Asia" },
  { label: "Togo", continent: "Africa" },
  { label: "Tokelau", continent: "Oceania" },
  { label: "Tonga", continent: "Oceania" },
  { label: "Trinidad and Tobago", continent: "North America" },
  { label: "Tunisia", continent: "Africa" },
  { label: "Turkey", continent: "Europe" },
  { label: "Turkmenistan", continent: "Asia" },
  { label: "Turks and Caicos Islands", continent: "North America" },
  { label: "Tuvalu", continent: "Oceania" },
  { label: "Uganda", continent: "Africa" },
  { label: "Ukraine", continent: "Europe" },
  { label: "United Arab Emirates", continent: "Asia" },
  { label: "United Kingdom", continent: "Europe" },
  { label: "United States", continent: "North America" },
  { label: "Uruguay", continent: "South America" },
  { label: "Uzbekistan", continent: "Asia" },
  { label: "Vanuatu", continent: "Oceania" },
  { label: "Vatican", continent: "Europe" },
  { label: "Venezuela", continent: "South America" },
  { label: "Vietnam", continent: "Asia" },
  { label: "Wallis and Futuna", continent: "Oceania" },
  { label: "Yemen", continent: "Asia" },
  { label: "Zambia", continent: "Africa" },
  { label: "Zimbabwe", continent: "Africa" },
];

export const recommendationDict = {
  new_deaths: "euclidean",
  new_cases: "chebyshev",
  new_deaths_per_million: "euclidean",
  new_cases_per_million: "chebyshev",
  biweekly_cases_per_million: "euclidean",
  biweekly_deaths_per_million: "chebyshev",
  biweekly_cases: "euclidean",
  biweekly_deaths: "chebyshev",
  weekly_cases_per_million: "euclidean",
  weekly_deaths_per_million: "chebyshev",
  weekly_cases: "euclidean",
  weekly_deaths: "chebyshev",
};
