CREATE
  (`0` :VisFunction {id:"LineChart",type:"plot"}) ,
  (`2` :VisFunction {id:"TopLevelOverviewScreenA",type:"overview"}) ,
  (`8` :URL {id:"/scotland/overview/cumulative",url:"vis.scrc.uk",type:"overview"}) ,
  (`9` :URL {id:"/scotland/overview/cumulative/nhs_ayrshire_arran",url:"vis.scrc.uk",type:"details"}) ,
  (`10` :Data {id:"/scotland/cumulative",type:"table",url:"vis.scrc.uk/api/v1",title:"Cum No of Cases Tested Positive"}) ,
  (`11` :Data {id:"/scotland/cumulative/nhs_ayrshire_arran",type:"row",title:"some title",url:"vis.scrc.uk/api/v1"}) ,
  (`12` :URL {id:"/scotland/overview/cumulative/nhs_borders",url:"vis.scrc.uk",type:"details"}) ,
  (`13` :Data {id:"/scotland/cumulative/nhs_borders",type:"row",title:"some title",url:"vis.scrc.uk/api/v1"}) ,
  (`14` :URL {id:"/scotland/overview/cumulative/nhs_dumfries_galloway",url:"vis.scrc.uk",type:"details"}) ,
  (`15` :Data {id:"/scotland/cumulative/nhs_dumfries_galloway",type:"row",title:"some title",url:"vis.scrc.uk/api/v1"}) ,
  (`2`)-[:`RELATED_TO` ]->(`8`),
  (`0`)-[:`RELATED_TO` ]->(`9`),
  (`10`)-[:`RELATED_TO` ]->(`8`),
  (`11`)-[:`RELATED_TO` ]->(`9`),
  (`8`)-[:`RELATED_TO` ]->(`9`),
  (`8`)-[:`RELATED_TO` ]->(`12`),
  (`8`)-[:`RELATED_TO` ]->(`14`),
  (`13`)-[:`RELATED_TO` ]->(`12`),
  (`15`)-[:`RELATED_TO` ]->(`14`),
  (`0`)-[:`RELATED_TO` ]->(`12`),
  (`0`)-[:`RELATED_TO` ]->(`14`)